<?php

declare(strict_types=1);

/**
 * Copyright 2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 */

namespace Horde\Hordectl\Service\WebserverConfig;

/**
 * Emits a distro-specific README next to the generated tree.
 *
 * The README explains where each file goes on the major distros and
 * how to reproduce THIS PARTICULAR RUN. Reproducer text is tier-aware:
 * a config generated from the live registry does not print a
 * synthesis command, and vice versa. Kept as a separate service so
 * its content evolves independently of the flavor emitters.
 */
final class ReadmeEmitter
{
    public function emit(
        GenerationContext $context,
        string $outputDir,
        string $serverroot,
    ): EmitEntry {
        return new EmitEntry(
            $outputDir . '/README.md',
            $this->render($context, $serverroot),
        );
    }

    private function render(GenerationContext $context, string $serverroot): string
    {
        return match ($context->flavor) {
            'apache-vhost' => $this->apacheReadme($context, $serverroot),
            'nginx' => $this->nginxReadme($context, $serverroot),
            'htaccess' => $this->htaccessReadme($context),
            default => "# " . $context->flavor . "\nGenerated by hordectl.\n",
        };
    }

    /**
     * Provenance paragraph plus the reproducer command. This is the
     * only tier-sensitive block in the README; the install / layout
     * sections that follow are identical across tiers.
     */
    private function provenance(GenerationContext $context): string
    {
        $reproducer = $context->reproducer();
        return match ($context->tier) {
            'live-registry' => <<<MD
## Provenance

This configuration was generated by reading the installation's **live
registry** via the admin API. Re-running the same command re-queries the
target and picks up any registry drift:

    {$reproducer}

MD,
            'stdin-yaml' => <<<MD
## Provenance

This configuration was generated from a **YAML registry payload piped in
on stdin**. To reproduce, feed the same payload back in. The typical
capture command is:

    hordectl query registry > registry.yaml

Then regenerate:

    {$reproducer} < registry.yaml

MD,
            'defaults' => <<<MD
## Provenance

This configuration was generated from the **vanilla Horde 6 bundle
layout** using `--default-url` and `--root-bundle-path`. It is
self-contained and does not depend on a running registry. Re-running the
same command produces identical output:

    {$reproducer}

MD,
            default => "## Provenance\n\nUnknown input tier: " . $context->tier . ".\n\n",
        };
    }

    private function apacheReadme(GenerationContext $context, string $serverroot): string
    {
        $provenance = $this->provenance($context);
        return <<<MD
# hordectl apache-vhost output

Two-tier layout:

- `sites/*.conf` is **drop-in-ready**. Each file is a complete `<VirtualHost>`
  block that goes into your distro's sweep directory.
- `horde-includes/` is a **support tree**. The vhost files reference it by
  absolute paths under Apache ServerRoot (currently `{$serverroot}`).
  You copy this tree once and never touch it again.

{$provenance}
## Install (per distro)

### Debian / Ubuntu

    sudo cp -r horde-includes/ /etc/apache2/
    sudo cp sites/*.conf /etc/apache2/sites-available/
    sudo a2ensite <host>          # one per site file
    sudo systemctl reload apache2

### openSUSE / SLES

    sudo cp -r horde-includes/ /etc/apache2/
    sudo cp sites/*.conf /etc/apache2/vhosts.d/
    sudo systemctl reload apache2

### RHEL / Fedora / CentOS / Rocky

RHEL-family distros use `/etc/httpd` as their ServerRoot. This generator ran
with `--apache-serverroot={$serverroot}`. If that does not match your target
system, regenerate with `--apache-serverroot=/etc/httpd`.

    sudo cp -r horde-includes/ /etc/httpd/
    sudo cp sites/*.conf /etc/httpd/conf.d/
    sudo systemctl reload httpd

## Layout

```
sites/                          <-- copy into sites-available / vhosts.d / conf.d
    <host>.conf
horde-includes/                 <-- copy under Apache ServerRoot
    apps/
        <app>.conf              <-- per-app <Directory> block, forbid rules
    tls/
        <host>.conf             <-- operator-owned TLS knobs (write-once sketch)
    local/
        <host>.conf             <-- operator-owned override snippet
                                    (also write-once; hordectl never touches it)
```

## Regeneration

Regenerating with the same inputs produces identical output. TLS and local
snippets are operator-owned. hordectl writes an initial sketch the first time
and never overwrites either file thereafter, even under `--force`.

## Prerequisites

- Apache 2.4+ with `mod_rewrite`, `mod_authz_core`, `mod_proxy_fcgi`
- php-fpm listening on the socket named in each vhost's Prerequisites banner
- Every `<Directory>` block sets `AllowOverride None`. Stale `.htaccess`
  files under the served tree are silently ignored on purpose.
MD;
    }

    private function nginxReadme(GenerationContext $context, string $prefix): string
    {
        $provenance = $this->provenance($context);
        return <<<MD
# hordectl nginx output

Two-tier layout:

- `sites/*.conf` is **drop-in-ready**. Each file is a complete `server { }`
  block that goes into your distro's sweep directory.
- `horde-includes/` is a **support tree**. The site files reference it by
  absolute paths under nginx prefix (currently `{$prefix}`). You copy this
  tree once and never touch it again.

{$provenance}
## Install (per distro)

### Debian / Ubuntu

    sudo cp -r horde-includes/ /etc/nginx/
    sudo cp sites/*.conf /etc/nginx/sites-available/
    sudo ln -s /etc/nginx/sites-available/<host>.conf /etc/nginx/sites-enabled/
    sudo systemctl reload nginx

### openSUSE / SLES

    sudo cp -r horde-includes/ /etc/nginx/
    sudo cp sites/*.conf /etc/nginx/vhosts.d/
    sudo systemctl reload nginx

### RHEL / Fedora / CentOS / Rocky

    sudo cp -r horde-includes/ /etc/nginx/
    sudo cp sites/*.conf /etc/nginx/conf.d/
    sudo systemctl reload nginx

## Layout

```
sites/                              <-- copy into sites-available / vhosts.d / conf.d
    <host>.conf
horde-includes/                     <-- copy under nginx prefix
    apps/
        <app>.conf                  <-- per-app location blocks
    tls/
        <host>.conf                 <-- operator-owned TLS knobs (write-once sketch)
    local.d/
        <host>/                     <-- operator-owned override snippets
            *.conf                      (glob-included, safe if empty or absent)
```

## Regeneration

Regenerating with the same inputs produces identical output. TLS sketches
and `local.d/` snippets are operator-owned. hordectl writes an initial sketch
the first time and never overwrites either file thereafter.

## Prerequisites

- nginx 1.18+
- php-fpm listening on the socket named in each site's Prerequisites banner
- `fastcgi_param HTTP_AUTHORIZATION \$http_authorization;` is baked into every
  emitted site block so Bearer-token auth for REST/RPC endpoints works.
MD;
    }

    private function htaccessReadme(GenerationContext $context): string
    {
        $provenance = $this->provenance($context);
        return <<<MD
# hordectl htaccess output

One `.htaccess` file per served directory, mirroring the legacy Horde 5 shape
but populated from the current registry.

{$provenance}
## Install

Copy the generated tree under each app's fileroot:

    sudo cp -r <app>/ /path/to/vendor/horde/<app>/

or use the tree in place if your bundle already ships under the paths the
generator computed.

## Prerequisites

- Apache 2.4+ with `mod_rewrite` and `mod_authz_core`
- `AllowOverride FileInfo AuthConfig` (or `All`) at the parent `<Directory>`.
  htaccess is silently ignored when `AllowOverride None`.
- `Options +FollowSymLinks` (or `+SymLinksIfOwnerMatch`) if the docroot uses
  symlinks.

## Limitations

- Cannot follow registry entries whose webroot is on a different host. Use
  the `apache-vhost` or `nginx` flavor for per-vhost setups.
- Silently ineffective on `AllowOverride None`.
- Slower than a vhost-based setup: Apache stats every parent directory of
  every request looking for `.htaccess` files.

## Regeneration

Regenerating with the same inputs produces identical output. There are no
operator-owned files in this flavor.
MD;
    }
}
