<?php

declare(strict_types=1);

/**
 * Copyright 2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 */

namespace Horde\Hordectl\Service\WebserverConfig;

/**
 * Shared rendering primitives used by every flavor emitter.
 *
 * Pure functions of their inputs. Callers pass already-resolved
 * strings; this service produces well-formed comment blocks and
 * dispatches "what dispatcher does this app carry" heuristics.
 */
final class RenderHelper
{
    /** @var list<string> Directories that must never be web-servable. */
    public array $forbiddenDirs = [
        'lib',
        'config',
        'templates',
        'locale',
        'bin',
        'scripts',
        'data',
        'migration',
    ];

    /**
     * Renders the Prerequisites/Limitations comment block prepended
     * to every generated file. Flavor-specific detail comes from the
     * caller as a list of body lines.
     *
     * @param list<string> $body
     */
    public function prerequisitesHeader(string $flavor, array $body): string
    {
        $out = "# Generated by hordectl webserver-config " . $flavor . "\n";
        $out .= "# Regenerate to pick up registry changes. Do not edit by hand.\n";
        $out .= "#\n";
        foreach ($body as $line) {
            $out .= '# ' . $line . "\n";
        }
        $out .= "#\n\n";
        return $out;
    }

    /**
     * Picks the front-controller filename for an app based on which
     * dispatcher its fileroot actually carries. Falls back to
     * rampage.php for synthetic entries whose fileroot may not exist
     * yet.
     */
    public function frontControllerFor(AppEntry $app): string
    {
        if (is_file($app->fileroot . '/rampage.php')) {
            return 'rampage.php';
        }
        if (is_file($app->fileroot . '/dispatcher.php')) {
            return 'dispatcher.php';
        }
        return 'rampage.php';
    }

    /**
     * @param list<AppEntry> $apps
     */
    public function anyTls(array $apps): bool
    {
        foreach ($apps as $app) {
            if ($app->isTls()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Renders the operator-owned TLS sketch. Contents differ per
     * flavor (Apache vs nginx directive names).
     */
    public function tlsSketch(string $host, string $flavor): string
    {
        return match ($flavor) {
            'apache' => $this->apacheTlsSketch($host),
            'nginx' => $this->nginxTlsSketch($host),
            default => "# unknown flavor: " . $flavor . "\n",
        };
    }

    private function apacheTlsSketch(string $host): string
    {
        return "# hordectl webserver-config apache-vhost tls sketch for " . $host . "\n"
            . "# This file is owned by the operator. hordectl writes it once and never\n"
            . "# overwrites it, even under --force. Fill in the knobs that fit your\n"
            . "# deployment.\n"
            . "#\n"
            . "# Common shapes:\n"
            . "#\n"
            . "#   Let's Encrypt via certbot:\n"
            . "#     SSLCertificateFile      /etc/letsencrypt/live/" . $host . "/fullchain.pem\n"
            . "#     SSLCertificateKeyFile   /etc/letsencrypt/live/" . $host . "/privkey.pem\n"
            . "#\n"
            . "#   Manual certs:\n"
            . "#     SSLCertificateFile      /etc/ssl/certs/" . $host . ".crt\n"
            . "#     SSLCertificateKeyFile   /etc/ssl/private/" . $host . ".key\n"
            . "#     SSLCertificateChainFile /etc/ssl/certs/" . $host . "-chain.crt\n"
            . "#\n"
            . "#   Cipher / protocol tuning, HSTS, OCSP stapling, session cache: your call.\n"
            . "#\n"
            . "# SSLEngine on\n"
            . "# SSLProtocol -all +TLSv1.2 +TLSv1.3\n"
            . "# Header always set Strict-Transport-Security \"max-age=31536000; includeSubDomains\"\n";
    }

    private function nginxTlsSketch(string $host): string
    {
        return "# hordectl webserver-config nginx tls sketch for " . $host . "\n"
            . "# This file is owned by the operator. hordectl writes it once and never\n"
            . "# overwrites it, even under --force. Fill in the knobs that fit your\n"
            . "# deployment.\n"
            . "#\n"
            . "# Common shapes:\n"
            . "#\n"
            . "#   Let's Encrypt via certbot:\n"
            . "#     ssl_certificate     /etc/letsencrypt/live/" . $host . "/fullchain.pem;\n"
            . "#     ssl_certificate_key /etc/letsencrypt/live/" . $host . "/privkey.pem;\n"
            . "#\n"
            . "#   Manual certs:\n"
            . "#     ssl_certificate     /etc/ssl/certs/" . $host . ".crt;\n"
            . "#     ssl_certificate_key /etc/ssl/private/" . $host . ".key;\n"
            . "#\n"
            . "#   Cipher / protocol tuning, HSTS, OCSP stapling: your call.\n"
            . "#\n"
            . "# ssl_protocols       TLSv1.2 TLSv1.3;\n"
            . "# add_header          Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n";
    }

    /**
     * Returns the default php-fpm handler for the current PHP.
     * Assumes Ubuntu/Debian layout (which is what CI uses).
     */
    public function defaultPhpHandler(): string
    {
        return sprintf(
            'unix-socket:/run/php/php%d.%d-fpm.sock',
            PHP_MAJOR_VERSION,
            PHP_MINOR_VERSION,
        );
    }

    /**
     * Parses a --php-handler spec into a [directive, label] pair
     * suitable for the given flavor.
     *
     * @return array{0: string, 1: string}
     */
    public function phpHandler(string $spec, string $flavor): array
    {
        [$shape, $endpoint] = array_pad(explode(':', $spec, 2), 2, '');
        return match ($flavor) {
            'apache' => match ($shape) {
                'unix-socket' => [
                    'SetHandler "proxy:unix:' . $endpoint . '|fcgi://localhost"',
                    'unix-socket:' . $endpoint,
                ],
                'tcp' => [
                    'SetHandler "proxy:fcgi://' . $endpoint . '"',
                    'tcp:' . $endpoint,
                ],
                default => [
                    'SetHandler "proxy:unix:/run/php/php-fpm.sock|fcgi://localhost"',
                    'unknown-shape:' . $spec,
                ],
            },
            'nginx' => match ($shape) {
                'unix-socket' => ['fastcgi_pass unix:' . $endpoint . ';', 'unix-socket:' . $endpoint],
                'tcp' => ['fastcgi_pass ' . $endpoint . ';', 'tcp:' . $endpoint],
                default => ['fastcgi_pass unix:/run/php/php-fpm.sock;', 'unknown-shape:' . $spec],
            },
            default => ['', ''],
        };
    }
}
